# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stefan Nožinić
email: stefan@lugons.org
description: > # this means to ignore newlines until "baseurl:"
  This is my blog where I will express my thoughts about everything which I'm interested in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fantastic001.github.io" # the base hostname & protocol for your site
twitter_username: snstefan5
github_username:  fantastic001
linkedin_url: https://www.linkedin.com/in/stefan-no%C5%BEini%C4%87-222b9b68

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
